{"name": "Проверка получения заказа с указанием несуществующнго track номера - код ответа 404", "status": "passed", "description": "При отправке запроса с указанием несуществующего track номера в query параметре на ручку GET /api/v1/orders/track возвращается код ответа 404 с текстом \"Заказ не найден\"", "steps": [{"name": "Отправить запрос на получение заказа по номеру GET /api/v1/orders/track", "status": "passed", "parameters": [{"name": "query", "value": "'?t=0000'"}], "start": 1725454020741, "stop": 1725454020825}], "start": 1725454020741, "stop": 1725454020825, "uuid": "f54448d2-98e4-4fea-97a5-7654425b52cb", "historyId": "1476165939bf899b85c6c87157bb9e9e", "testCaseId": "1476165939bf899b85c6c87157bb9e9e", "fullName": "tests.test_get_order_by_track.TestGetOrderByTrack#test_get_order_with_not_existing_track_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_track"}, {"name": "subSuite", "value": "TestGetOrderByTrack"}, {"name": "host", "value": "poccona"}, {"name": "thread", "value": "24200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_track"}]}